### ISSUE TITLE
Enable Lossless compression for transparent PNG

### ISSUE THREAD

**Issue by creativesuspects** [yawkale/Dyfort.Umbraco.AutoImageOptimze#1]
It looks like you used the code from [this forum thread](https://our.umbraco.com/forum/using-umbraco-and-getting-started/109299-umbraco-10-webp-file-much-larger-than-png) to create this package. You should consider adding the following code to enable lossless compression for transparent PNG's, see the test results I mentioned in the forum thread. Without this code some transparent PNG's are converted to fairly large WEBP files which defeats the purpose of this package.

```
    options.OnBeforeSaveAsync = c =>
    {
        if (c.Encoder.GetType().Name == "WebpEncoder" && c.Image.PixelType.BitsPerPixel == 32)
        {
            c.Encoder = new WebpEncoder()
            {
                FileFormat = WebpFileFormatType.Lossless,
            };
        }
        return Task.CompletedTask;
    };
```

**Comment by cvocvo** [comment]
I was actually just looking for the source code to try to find this as well. It looks to me like this is included? https://github.com/yawkale/Dyfort.Umbraco.AutoImageOptimze/blob/1.0.2/Dyfort.Umbraco.AutoImageOptimze/AutoImageOptimizeComposer.cs#L35

(at least on v1.0.2 -- we're on Umbraco v10 because LTS)

**Comment by creativesuspects** [comment]
Ah, you're right. I was looking at the 2.0.0 branch. So this issue only applies to that version.

**Comment by yawkale** [comment]
this issue was solved in ImageSharp 3, I belive we don't need it
